### ISSUE TITLE
[BUG] Self-hosted Obico refuses to start: BadDsn error despite SENTRY_DSN not being set

### ISSUE THREAD

**Issue by nullfact0r** [TheSpaghettiDetective/OctoPrint-Obico#202]
**Describe the bug**
I was recently redoing my homelab infrastructure and was trying to reinstall self-hosted Obico. I did the steps as with my first install (clone git repo, compose up, hoping for profit)

**To Reproduce**
1. Clone the git repository
2. Run `docker-compose up -d`
3. Check `docker ps -a`
4. Redis and ml_api start successfully, web and tasks crashes with the following error:
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/config/settings.py", line 326, in <module>
    release=VERSION,
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/client.py", line 86, in __init__
    self._init_impl()
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/client.py", line 108, in _init_impl
    self.transport = make_transport(self.options)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/transport.py", line 529, in make_transport
    return transport_cls(options)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/transport.py", line 142, in __init__
    Transport.__init__(self, options)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/transport.py", line 56, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/utils.py", line 165, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme ''
```

**Deployment information:**
 - OS: Rocky Linux 9 in LXC on Proxmox (FUSE and Nesting enabled; Privileged container)

The SENTRY_DSN variable was not set. Other things I tried included removing the sentry-related block from `settings.py`, setting a valid DSN (both current Sentry and legacy) and manually setting SENTRY_DSN to `None`.

**Comment by nullfact0r** [comment]
Wait sorry, I accidentally opened the issue on the wrong repository
